import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { HiPrinter, HiDownload, HiArrowLeft } from 'react-icons/hi';
import { useAuth } from '../../context/AuthContext';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Calculate hours between two "HH:MM" strings
function calcHours(start, end) {
  const [sh, sm] = start.split(':').map(Number);
  const [eh, em] = end.split(':').map(Number);
  return Math.max(0, (eh * 60 + em - (sh * 60 + sm)) / 60);
}

export default function PrintStudyLoad() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const printRef = useRef();

  const [courses, setCourses] = useState([]);
  const [schedules, setSchedules] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [coursesRes, schedulesRes] = await Promise.all([
          api.get('/courses/my-courses'),
          api.get('/schedules/my-schedule'),
        ]);
        setCourses(coursesRes.data);
        setSchedules(schedulesRes.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const totalUnits = courses.reduce((sum, c) => sum + (c.units || 0), 0);

  // Total hours per week = sum of all schedule durations
  const totalHoursPerWeek = schedules.reduce((sum, s) => sum + calcHours(s.startTime, s.endTime), 0);

  const handlePrint = () => window.print();

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('TROPHE UNIVERSITY', 105, 20, { align: 'center' });

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('Smart Campus Management System', 105, 28, { align: 'center' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL STUDY LOAD', 105, 37, { align: 'center' });

    doc.setLineWidth(0.5);
    doc.line(15, 41, 195, 41);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Student Name: ${user.firstName} ${user.lastName}`, 15, 49);
    doc.text(`Student ID: ${user.studentId || 'N/A'}`, 15, 56);
    doc.text(`Department: ${user.department || 'N/A'}`, 15, 63);
    doc.text(`School Year: 2024-2025`, 120, 49);
    doc.text(`Semester: 1st Semester`, 120, 56);
    doc.text(`Date Printed: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 120, 63);

    doc.line(15, 67, 195, 67);

    autoTable(doc, {
      startY: 71,
      head: [['Course Code', 'Course Name', 'Type', 'Units', 'Hrs/Wk', 'Schedule', 'Room', 'Instructor']],
      body: courses.map((c) => {
        const cs = schedules.filter((s) => s.course?._id === c._id);
        const scheduleStr = cs.length ? cs.map((s) => `${s.day} ${s.startTime}-${s.endTime}`).join('\n') : 'TBA';
        const roomStr = cs.length ? cs.map((s) => s.room || 'TBA').join('\n') : 'TBA';
        const hrs = cs.reduce((sum, s) => sum + calcHours(s.startTime, s.endTime), 0);
        const instructor = c.faculty ? `${c.faculty.firstName} ${c.faculty.lastName}` : 'TBA';
        const typeLabel = c.type === 'laboratory' ? 'Lab' : 'Lec';
        return [c.courseCode, c.courseName, typeLabel, c.units, hrs > 0 ? `${hrs}h` : 'TBA', scheduleStr, roomStr, instructor];
      }),
      foot: [['', 'TOTALS', '', totalUnits, `${totalHoursPerWeek}h/wk`, '', '', '']],
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      footStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: {
        0: { cellWidth: 22 },
        1: { cellWidth: 40 },
        2: { cellWidth: 14 },
        3: { cellWidth: 12, halign: 'center' },
        4: { cellWidth: 14, halign: 'center' },
        5: { cellWidth: 30 },
        6: { cellWidth: 20 },
        7: { cellWidth: 28 },
      },
    });

    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(9);
    doc.text('This is an official document generated by the Trophe Smart Campus Management System.', 105, finalY, { align: 'center' });
    doc.text('Unauthorized alteration of this document is prohibited.', 105, finalY + 5, { align: 'center' });

    doc.save(`StudyLoad_${user.firstName}_${user.lastName}_${user.studentId || 'student'}.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600" />
      </div>
    );
  }

  return (
    <>
      {/* Action Bar */}
      <div className="no-print fixed top-0 left-0 right-0 z-50 bg-slate-900 border-b border-slate-700 px-6 py-3 flex items-center justify-between">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-slate-400 hover:text-slate-100 transition-colors">
          <HiArrowLeft className="w-5 h-5" />
          <span className="text-sm">Back</span>
        </button>
        <div className="flex items-center gap-3">
          <button onClick={handleDownloadPDF} className="flex items-center gap-2 bg-slate-700 hover:bg-slate-600 text-slate-100 px-4 py-2 rounded-lg text-sm transition-colors">
            <HiDownload className="w-4 h-4" /> Download PDF
          </button>
          <button onClick={handlePrint} className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm transition-colors">
            <HiPrinter className="w-4 h-4" /> Print
          </button>
        </div>
      </div>

      {/* Preview */}
      <div className="min-h-screen bg-gray-100 no-print pt-16 pb-8 px-4 flex justify-center">
        <div ref={printRef} className="bg-white w-full max-w-4xl shadow-lg rounded-lg overflow-hidden print-document">
          <PrintContent user={user} courses={courses} schedules={schedules} totalUnits={totalUnits} totalHoursPerWeek={totalHoursPerWeek} />
        </div>
      </div>

      {/* Print-only */}
      <div className="hidden print:block print-document">
        <PrintContent user={user} courses={courses} schedules={schedules} totalUnits={totalUnits} totalHoursPerWeek={totalHoursPerWeek} />
      </div>

      <style>{`
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
          .print-document { display: block !important; box-shadow: none !important; }
          @page { size: A4; margin: 15mm; }
        }
      `}</style>
    </>
  );
}

function PrintContent({ user, courses, schedules, totalUnits, totalHoursPerWeek }) {
  return (
    <div className="p-10 text-gray-900 font-sans">
      {/* University Header */}
      <div className="text-center border-b-2 border-blue-700 pb-6 mb-6">
        <div className="flex items-center justify-center gap-4 mb-2">
          <svg width="56" height="56" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="50" cy="50" r="48" fill="#1e3a8a" />
            <g fill="#22c55e" opacity="0.9">
              <ellipse cx="14" cy="50" rx="5" ry="2.5" transform="rotate(-10 14 50)" />
              <ellipse cx="16" cy="40" rx="5" ry="2.5" transform="rotate(-30 16 40)" />
              <ellipse cx="21" cy="31" rx="5" ry="2.5" transform="rotate(-50 21 31)" />
              <ellipse cx="29" cy="24" rx="5" ry="2.5" transform="rotate(-70 29 24)" />
              <ellipse cx="39" cy="19" rx="5" ry="2.5" transform="rotate(-85 39 19)" />
              <ellipse cx="14" cy="60" rx="5" ry="2.5" transform="rotate(10 14 60)" />
              <ellipse cx="16" cy="70" rx="5" ry="2.5" transform="rotate(30 16 70)" />
              <ellipse cx="21" cy="79" rx="5" ry="2.5" transform="rotate(50 21 79)" />
              <ellipse cx="29" cy="86" rx="5" ry="2.5" transform="rotate(70 29 86)" />
              <ellipse cx="39" cy="91" rx="5" ry="2.5" transform="rotate(85 39 91)" />
              <ellipse cx="86" cy="50" rx="5" ry="2.5" transform="rotate(10 86 50)" />
              <ellipse cx="84" cy="40" rx="5" ry="2.5" transform="rotate(30 84 40)" />
              <ellipse cx="79" cy="31" rx="5" ry="2.5" transform="rotate(50 79 31)" />
              <ellipse cx="71" cy="24" rx="5" ry="2.5" transform="rotate(70 71 24)" />
              <ellipse cx="61" cy="19" rx="5" ry="2.5" transform="rotate(85 61 19)" />
              <ellipse cx="86" cy="60" rx="5" ry="2.5" transform="rotate(-10 86 60)" />
              <ellipse cx="84" cy="70" rx="5" ry="2.5" transform="rotate(-30 84 70)" />
              <ellipse cx="79" cy="79" rx="5" ry="2.5" transform="rotate(-50 79 79)" />
              <ellipse cx="71" cy="86" rx="5" ry="2.5" transform="rotate(-70 71 86)" />
              <ellipse cx="61" cy="91" rx="5" ry="2.5" transform="rotate(-85 61 91)" />
            </g>
            <path d="M 50 93 Q 42 90 36 85" stroke="#16a34a" strokeWidth="1.5" fill="none" strokeLinecap="round" />
            <path d="M 50 93 Q 58 90 64 85" stroke="#16a34a" strokeWidth="1.5" fill="none" strokeLinecap="round" />
            <circle cx="50" cy="93" r="2" fill="#fbbf24" />
            <circle cx="50" cy="48" r="28" fill="#0f172a" opacity="0.7" />
            <ellipse cx="50" cy="58" rx="12" ry="14" fill="#1e40af" />
            <ellipse cx="39" cy="58" rx="6" ry="10" fill="#1d4ed8" transform="rotate(-10 39 58)" />
            <ellipse cx="61" cy="58" rx="6" ry="10" fill="#1d4ed8" transform="rotate(10 61 58)" />
            <circle cx="50" cy="42" r="11" fill="#1e40af" />
            <polygon points="43,33 40,26 46,31" fill="#1e40af" />
            <polygon points="57,33 60,26 54,31" fill="#1e40af" />
            <circle cx="44" cy="42" r="5.5" fill="#fbbf24" />
            <circle cx="44" cy="42" r="3.5" fill="#1e3a8a" />
            <circle cx="44" cy="42" r="2" fill="#0f172a" />
            <circle cx="45.5" cy="40.5" r="0.8" fill="white" />
            <circle cx="56" cy="42" r="5.5" fill="#fbbf24" />
            <circle cx="56" cy="42" r="3.5" fill="#1e3a8a" />
            <circle cx="56" cy="42" r="2" fill="#0f172a" />
            <circle cx="57.5" cy="40.5" r="0.8" fill="white" />
            <polygon points="50,44 47,48 53,48" fill="#fbbf24" />
          </svg>
          <div className="text-left">
            <h1 className="text-2xl font-bold text-blue-800 tracking-wide" style={{ fontFamily: 'Georgia, serif' }}>ΤΡΟΦΗ UNIVERSITY</h1>
            <p className="text-sm text-gray-500 tracking-widest uppercase" style={{ letterSpacing: '0.15em' }}>Trophe · Smart Campus Management</p>
          </div>
        </div>
        <h2 className="text-lg font-bold text-gray-700 mt-3 tracking-widest uppercase">Official Study Load</h2>
      </div>

      {/* Student Info */}
      <div className="grid grid-cols-2 gap-x-8 gap-y-2 mb-6 text-sm">
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Student Name:</span>
          <span className="text-gray-900 font-medium">{user.firstName} {user.lastName}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">School Year:</span>
          <span className="text-gray-900">2024-2025</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Student ID:</span>
          <span className="text-gray-900">{user.studentId || 'N/A'}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Semester:</span>
          <span className="text-gray-900">1st Semester</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Department:</span>
          <span className="text-gray-900">{user.department || 'N/A'}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Date Printed:</span>
          <span className="text-gray-900">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
        </div>
      </div>

      {/* Courses Table */}
      <table className="w-full border-collapse text-sm mb-6">
        <thead>
          <tr className="bg-blue-700 text-white">
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Course Code</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Course Name</th>
            <th className="border border-blue-600 px-3 py-2.5 text-center font-semibold">Type</th>
            <th className="border border-blue-600 px-3 py-2.5 text-center font-semibold">Units</th>
            <th className="border border-blue-600 px-3 py-2.5 text-center font-semibold">Hrs/Wk</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Schedule</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Room</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Instructor</th>
          </tr>
        </thead>
        <tbody>
          {courses.length === 0 ? (
            <tr>
              <td colSpan={8} className="border border-gray-300 px-3 py-4 text-center text-gray-400">No enrolled courses</td>
            </tr>
          ) : (
            courses.map((course, idx) => {
              const cs = schedules.filter((s) => s.course?._id === course._id);
              const hrs = cs.reduce((sum, s) => sum + calcHours(s.startTime, s.endTime), 0);
              const isLab = course.type === 'laboratory';
              return (
                <tr key={course._id} className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                  <td className="border border-gray-300 px-3 py-2.5 font-medium text-blue-700">{course.courseCode}</td>
                  <td className="border border-gray-300 px-3 py-2.5">{course.courseName}</td>
                  <td className="border border-gray-300 px-3 py-2.5 text-center">
                    <span className={`inline-block text-xs font-semibold px-2 py-0.5 rounded-full ${isLab ? 'bg-purple-100 text-purple-700' : 'bg-green-100 text-green-700'}`}>
                      {isLab ? 'Lab' : 'Lec'}
                    </span>
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5 text-center font-semibold">{course.units}</td>
                  <td className="border border-gray-300 px-3 py-2.5 text-center font-semibold">
                    {hrs > 0 ? `${hrs}h` : <span className="text-gray-400 font-normal">TBA</span>}
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {cs.length === 0 ? (
                      <span className="text-gray-400">TBA</span>
                    ) : (
                      <div className="space-y-0.5">
                        {cs.map((s, i) => (
                          <div key={i} className="text-xs">{s.day} {s.startTime}–{s.endTime}</div>
                        ))}
                      </div>
                    )}
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {cs.length === 0 ? (
                      <span className="text-gray-400">TBA</span>
                    ) : (
                      <div className="space-y-0.5">
                        {cs.map((s, i) => (
                          <div key={i} className="text-xs">{s.room || 'TBA'}</div>
                        ))}
                      </div>
                    )}
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {course.faculty ? `${course.faculty.firstName} ${course.faculty.lastName}` : <span className="text-gray-400">TBA</span>}
                  </td>
                </tr>
              );
            })
          )}
        </tbody>
        <tfoot>
          <tr className="bg-gray-100 font-semibold">
            <td colSpan={3} className="border border-gray-300 px-3 py-2.5 text-right text-gray-600">TOTALS:</td>
            <td className="border border-gray-300 px-3 py-2.5 text-center text-blue-700 font-bold text-base">{totalUnits}</td>
            <td className="border border-gray-300 px-3 py-2.5 text-center text-blue-700 font-bold text-base">{totalHoursPerWeek}h</td>
            <td colSpan={3} className="border border-gray-300 px-3 py-2.5 text-xs text-gray-500">
              {totalUnits} total units &nbsp;·&nbsp; {totalHoursPerWeek} hrs/week
            </td>
          </tr>
        </tfoot>
      </table>

      {/* Signature Section */}
      <div className="grid grid-cols-3 gap-8 mt-10">
        {['Student Signature', 'Adviser', 'Registrar'].map((label) => (
          <div key={label} className="text-center">
            <div className="border-b border-gray-400 mb-1 h-10" />
            <p className="text-xs font-semibold text-gray-600">{label}</p>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-200 text-center">
        <p className="text-xs text-gray-400">This is an official document generated by the Trophe Smart Campus Management System.</p>
        <p className="text-xs text-gray-400">Unauthorized alteration of this document is prohibited.</p>
      </div>
    </div>
  );
}
