import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { HiPrinter, HiDownload, HiArrowLeft } from 'react-icons/hi';
import { useAuth } from '../../context/AuthContext';
import api from '../../utils/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export default function PrintStudyLoad() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const printRef = useRef();

  const [courses, setCourses] = useState([]);
  const [schedules, setSchedules] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [coursesRes, schedulesRes] = await Promise.all([
          api.get('/courses/my-courses'),
          api.get('/schedules/my-schedule'),
        ]);
        setCourses(coursesRes.data);
        setSchedules(schedulesRes.data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const totalUnits = courses.reduce((sum, c) => sum + (c.units || 0), 0);

  const getScheduleForCourse = (courseId) => {
    return schedules
      .filter((s) => s.course?._id === courseId)
      .map((s) => `${s.day} ${s.startTime}–${s.endTime}`)
      .join(', ');
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('TROPHE UNIVERSITY', 105, 20, { align: 'center' });

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Smart Campus Management System', 105, 28, { align: 'center' });

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('OFFICIAL STUDY LOAD', 105, 38, { align: 'center' });

    // Divider
    doc.setLineWidth(0.5);
    doc.line(15, 42, 195, 42);

    // Student Info
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Student Name: ${user.firstName} ${user.lastName}`, 15, 50);
    doc.text(`Student ID: ${user.studentId || 'N/A'}`, 15, 57);
    doc.text(`Department: ${user.department || 'N/A'}`, 15, 64);
    doc.text(`School Year: 2024-2025`, 120, 50);
    doc.text(`Semester: 1st Semester`, 120, 57);
    doc.text(`Date Printed: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 120, 64);

    doc.line(15, 68, 195, 68);

    // Table
    autoTable(doc, {
      startY: 72,
      head: [['Course Code', 'Course Name', 'Units', 'Schedule', 'Room', 'Instructor']],
      body: courses.map((c) => {
        const courseSchedules = schedules.filter((s) => s.course?._id === c._id);
        const scheduleStr = courseSchedules.map((s) => `${s.day} ${s.startTime}-${s.endTime}`).join('\n');
        const roomStr = courseSchedules.map((s) => s.room || 'TBA').join('\n');
        const instructor = c.faculty ? `${c.faculty.firstName} ${c.faculty.lastName}` : 'TBA';
        return [c.courseCode, c.courseName, c.units, scheduleStr, roomStr, instructor];
      }),
      foot: [['', 'TOTAL UNITS', totalUnits, '', '', '']],
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      footStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(9);
    doc.text('This is an official document generated by the Trophe Smart Campus Management System.', 105, finalY, { align: 'center' });
    doc.text('Unauthorized alteration of this document is prohibited.', 105, finalY + 5, { align: 'center' });

    doc.save(`StudyLoad_${user.firstName}_${user.lastName}_${user.studentId || 'student'}.pdf`);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600" />
      </div>
    );
  }

  return (
    <>
      {/* Action Bar - hidden on print */}
      <div className="no-print fixed top-0 left-0 right-0 z-50 bg-slate-900 border-b border-slate-700 px-6 py-3 flex items-center justify-between">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-slate-400 hover:text-slate-100 transition-colors">
          <HiArrowLeft className="w-5 h-5" />
          <span className="text-sm">Back</span>
        </button>
        <div className="flex items-center gap-3">
          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 bg-slate-700 hover:bg-slate-600 text-slate-100 px-4 py-2 rounded-lg text-sm transition-colors"
          >
            <HiDownload className="w-4 h-4" />
            Download PDF
          </button>
          <button
            onClick={handlePrint}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm transition-colors"
          >
            <HiPrinter className="w-4 h-4" />
            Print
          </button>
        </div>
      </div>

      {/* Printable Document */}
      <div className="min-h-screen bg-gray-100 no-print pt-16 pb-8 px-4 flex justify-center">
        <div ref={printRef} className="bg-white w-full max-w-4xl shadow-lg rounded-lg overflow-hidden print-document">
          <PrintContent user={user} courses={courses} schedules={schedules} totalUnits={totalUnits} getScheduleForCourse={getScheduleForCourse} />
        </div>
      </div>

      {/* Print-only version */}
      <div className="hidden print:block print-document">
        <PrintContent user={user} courses={courses} schedules={schedules} totalUnits={totalUnits} getScheduleForCourse={getScheduleForCourse} />
      </div>

      <style>{`
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
          .print-document { display: block !important; box-shadow: none !important; }
          @page { size: A4; margin: 15mm; }
        }
      `}</style>
    </>
  );
}

function PrintContent({ user, courses, schedules, totalUnits, getScheduleForCourse }) {
  return (
    <div className="p-10 text-gray-900 font-sans">
      {/* University Header */}
      <div className="text-center border-b-2 border-blue-700 pb-6 mb-6">
        <div className="flex items-center justify-center gap-4 mb-2">
          {/* Greek owl logo inline SVG for print */}
          <svg width="56" height="56" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="50" cy="50" r="48" fill="#1e3a8a" />
            <g fill="#22c55e" opacity="0.9">
              <ellipse cx="14" cy="50" rx="5" ry="2.5" transform="rotate(-10 14 50)" />
              <ellipse cx="16" cy="40" rx="5" ry="2.5" transform="rotate(-30 16 40)" />
              <ellipse cx="21" cy="31" rx="5" ry="2.5" transform="rotate(-50 21 31)" />
              <ellipse cx="29" cy="24" rx="5" ry="2.5" transform="rotate(-70 29 24)" />
              <ellipse cx="39" cy="19" rx="5" ry="2.5" transform="rotate(-85 39 19)" />
              <ellipse cx="14" cy="60" rx="5" ry="2.5" transform="rotate(10 14 60)" />
              <ellipse cx="16" cy="70" rx="5" ry="2.5" transform="rotate(30 16 70)" />
              <ellipse cx="21" cy="79" rx="5" ry="2.5" transform="rotate(50 21 79)" />
              <ellipse cx="29" cy="86" rx="5" ry="2.5" transform="rotate(70 29 86)" />
              <ellipse cx="39" cy="91" rx="5" ry="2.5" transform="rotate(85 39 91)" />
              <ellipse cx="86" cy="50" rx="5" ry="2.5" transform="rotate(10 86 50)" />
              <ellipse cx="84" cy="40" rx="5" ry="2.5" transform="rotate(30 84 40)" />
              <ellipse cx="79" cy="31" rx="5" ry="2.5" transform="rotate(50 79 31)" />
              <ellipse cx="71" cy="24" rx="5" ry="2.5" transform="rotate(70 71 24)" />
              <ellipse cx="61" cy="19" rx="5" ry="2.5" transform="rotate(85 61 19)" />
              <ellipse cx="86" cy="60" rx="5" ry="2.5" transform="rotate(-10 86 60)" />
              <ellipse cx="84" cy="70" rx="5" ry="2.5" transform="rotate(-30 84 70)" />
              <ellipse cx="79" cy="79" rx="5" ry="2.5" transform="rotate(-50 79 79)" />
              <ellipse cx="71" cy="86" rx="5" ry="2.5" transform="rotate(-70 71 86)" />
              <ellipse cx="61" cy="91" rx="5" ry="2.5" transform="rotate(-85 61 91)" />
            </g>
            <path d="M 50 93 Q 42 90 36 85" stroke="#16a34a" strokeWidth="1.5" fill="none" strokeLinecap="round" />
            <path d="M 50 93 Q 58 90 64 85" stroke="#16a34a" strokeWidth="1.5" fill="none" strokeLinecap="round" />
            <circle cx="50" cy="93" r="2" fill="#fbbf24" />
            <circle cx="50" cy="48" r="28" fill="#0f172a" opacity="0.7" />
            <ellipse cx="50" cy="58" rx="12" ry="14" fill="#1e40af" />
            <ellipse cx="39" cy="58" rx="6" ry="10" fill="#1d4ed8" transform="rotate(-10 39 58)" />
            <ellipse cx="61" cy="58" rx="6" ry="10" fill="#1d4ed8" transform="rotate(10 61 58)" />
            <circle cx="50" cy="42" r="11" fill="#1e40af" />
            <polygon points="43,33 40,26 46,31" fill="#1e40af" />
            <polygon points="57,33 60,26 54,31" fill="#1e40af" />
            <circle cx="44" cy="42" r="5.5" fill="#fbbf24" />
            <circle cx="44" cy="42" r="3.5" fill="#1e3a8a" />
            <circle cx="44" cy="42" r="2" fill="#0f172a" />
            <circle cx="45.5" cy="40.5" r="0.8" fill="white" />
            <circle cx="56" cy="42" r="5.5" fill="#fbbf24" />
            <circle cx="56" cy="42" r="3.5" fill="#1e3a8a" />
            <circle cx="56" cy="42" r="2" fill="#0f172a" />
            <circle cx="57.5" cy="40.5" r="0.8" fill="white" />
            <polygon points="50,44 47,48 53,48" fill="#fbbf24" />
          </svg>
          <div className="text-left">
            <h1 className="text-2xl font-bold text-blue-800 tracking-wide" style={{ fontFamily: 'Georgia, serif' }}>ΤΡΟΦΗ UNIVERSITY</h1>
            <p className="text-sm text-gray-500 tracking-widest uppercase" style={{ letterSpacing: '0.15em' }}>Trophe · Smart Campus Management</p>
          </div>
        </div>
        <h2 className="text-lg font-bold text-gray-700 mt-3 tracking-widest uppercase">Official Study Load</h2>
      </div>

      {/* Student Information */}
      <div className="grid grid-cols-2 gap-x-8 gap-y-2 mb-6 text-sm">
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Student Name:</span>
          <span className="text-gray-900 font-medium">{user.firstName} {user.lastName}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">School Year:</span>
          <span className="text-gray-900">2024-2025</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Student ID:</span>
          <span className="text-gray-900">{user.studentId || 'N/A'}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Semester:</span>
          <span className="text-gray-900">1st Semester</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Department:</span>
          <span className="text-gray-900">{user.department || 'N/A'}</span>
        </div>
        <div className="flex gap-2">
          <span className="font-semibold text-gray-600 w-32 shrink-0">Date Printed:</span>
          <span className="text-gray-900">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
        </div>
      </div>

      {/* Courses Table */}
      <table className="w-full border-collapse text-sm mb-6">
        <thead>
          <tr className="bg-blue-700 text-white">
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Course Code</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Course Name</th>
            <th className="border border-blue-600 px-3 py-2.5 text-center font-semibold">Units</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Schedule</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Room</th>
            <th className="border border-blue-600 px-3 py-2.5 text-left font-semibold">Instructor</th>
          </tr>
        </thead>
        <tbody>
          {courses.length === 0 ? (
            <tr>
              <td colSpan={6} className="border border-gray-300 px-3 py-4 text-center text-gray-400">No enrolled courses</td>
            </tr>
          ) : (
            courses.map((course, idx) => {
              const courseSchedules = schedules.filter((s) => s.course?._id === course._id);
              return (
                <tr key={course._id} className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                  <td className="border border-gray-300 px-3 py-2.5 font-medium text-blue-700">{course.courseCode}</td>
                  <td className="border border-gray-300 px-3 py-2.5">{course.courseName}</td>
                  <td className="border border-gray-300 px-3 py-2.5 text-center font-semibold">{course.units}</td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {courseSchedules.length === 0 ? (
                      <span className="text-gray-400">TBA</span>
                    ) : (
                      <div className="space-y-0.5">
                        {courseSchedules.map((s, i) => (
                          <div key={i} className="text-xs">{s.day} {s.startTime}–{s.endTime}</div>
                        ))}
                      </div>
                    )}
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {courseSchedules.length === 0 ? (
                      <span className="text-gray-400">TBA</span>
                    ) : (
                      <div className="space-y-0.5">
                        {courseSchedules.map((s, i) => (
                          <div key={i} className="text-xs">{s.room || 'TBA'}</div>
                        ))}
                      </div>
                    )}
                  </td>
                  <td className="border border-gray-300 px-3 py-2.5">
                    {course.faculty ? `${course.faculty.firstName} ${course.faculty.lastName}` : <span className="text-gray-400">TBA</span>}
                  </td>
                </tr>
              );
            })
          )}
        </tbody>
        <tfoot>
          <tr className="bg-gray-100 font-semibold">
            <td colSpan={2} className="border border-gray-300 px-3 py-2.5 text-right">TOTAL UNITS:</td>
            <td className="border border-gray-300 px-3 py-2.5 text-center text-blue-700 font-bold text-base">{totalUnits}</td>
            <td colSpan={3} className="border border-gray-300 px-3 py-2.5"></td>
          </tr>
        </tfoot>
      </table>

      {/* Signature Section */}
      <div className="grid grid-cols-3 gap-8 mt-10">
        {['Student Signature', 'Adviser', 'Registrar'].map((label) => (
          <div key={label} className="text-center">
            <div className="border-b border-gray-400 mb-1 h-10" />
            <p className="text-xs font-semibold text-gray-600">{label}</p>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-200 text-center">
        <p className="text-xs text-gray-400">This is an official document generated by the Trophe Smart Campus Management System.</p>
        <p className="text-xs text-gray-400">Unauthorized alteration of this document is prohibited.</p>
      </div>
    </div>
  );
}
